# Generated by Django 4.1.13 on 2024-05-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('prediction', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
