# Generated by Django 4.1.13 on 2024-05-09 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd', '0002_tweet_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='rawPrediction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
