# Generated by Django 4.1.13 on 2024-05-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgd', '0003_tweet_rawprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='rawPrediction',
            new_name='rawPredictionArray',
        ),
    ]
