# Generated by Django 4.1.13 on 2024-05-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgd', '0005_tweet_tweetconent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='TweetConent',
            new_name='TweetContent',
        ),
    ]
