# Generated by Django 4.1.13 on 2024-05-11 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd', '0006_rename_tweetconent_tweet_tweetcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='cpu_usage',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='tweet',
            name='memory_usage',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='rawPredictionArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
